export const FONT_OPTIONS = [
  "system-ui",
  "ui-sans-serif",
  "ui-serif",
  "ui-monospace",
  "Arial",
  "Helvetica",
  "Georgia",
  "Times New Roman",
  "Courier New",
  "Comic Sans MS",
  "Trebuchet MS",
  "Verdana",
  "Impact",
  "Garamond",
  "Palatino",
  "Lucida Sans",
  "Lucida Console",
  "Tahoma",
  "Copperplate",
  "Futura",
  "Franklin Gothic Medium",
  "Gill Sans",
  "Baskerville",
  "Avenir",
  "Didot",
  "Montserrat",
  "Poppins",
  "Inter",
  "Roboto",
  "Merriweather",
  "Lora",
  "Playfair Display",
  "Nunito",
  "Oswald",
  "Raleway",
  "Source Sans Pro",
  "Quicksand",
  "Inconsolata",
  "JetBrains Mono",
  "Space Grotesk",
  "Space Mono",
  "Kanit",
  "Rubik",
  "DM Sans",
  "Manrope",
  "Work Sans",
  "Cabin",
  "Barlow",
  "Jost",
  "Sora"
] as const;
