export const FONT_OPTIONS: string[] = [
  "Inter, sans-serif",
  "DM Sans, sans-serif",
  "Rubik, sans-serif",
  "Nunito, sans-serif",
  "Poppins, sans-serif",
  "Montserrat, sans-serif",
  "Work Sans, sans-serif",
  "Figtree, sans-serif",
  "Raleway, sans-serif",
  "Noto Sans, sans-serif",
  "Merriweather, serif",
  "JetBrains Mono, monospace",
  "Plus Jakarta Sans, sans-serif",
  "Sora, sans-serif",
  "Manrope, sans-serif",
  "Space Grotesk, sans-serif",
  "Cabin, sans-serif",
  "Exo 2, sans-serif",
  "Karla, sans-serif",
  "Source Sans 3, sans-serif",
  "Urbanist, sans-serif",
  "Merriweather Sans, sans-serif",
  "DM Mono, monospace",
  "Fira Code, monospace",
  "Arial, sans-serif",
  "Georgia, serif",
  "Courier New, monospace",
  "Comic Sans MS, cursive",
  "Trebuchet MS, sans-serif",
  "Times New Roman, serif",
  "Verdana, sans-serif"
];
